# **PyTorch Fundamentals Exercise**



In [1]:
import torch

### **Q1 Create a random tensor with shape `(7, 7)`**


In [2]:
tensor = torch.rand(7, 7)
print(tensor)

tensor([[0.7547, 0.7721, 0.7709, 0.7560, 0.8898, 0.4408, 0.4095],
        [0.3981, 0.4256, 0.3498, 0.1219, 0.0887, 0.1458, 0.6637],
        [0.2982, 0.7054, 0.9767, 0.4932, 0.2714, 0.3983, 0.8872],
        [0.9609, 0.6115, 0.5429, 0.7856, 0.1826, 0.7050, 0.3405],
        [0.5977, 0.7557, 0.4604, 0.3232, 0.2555, 0.8911, 0.0197],
        [0.0040, 0.7182, 0.7601, 0.5136, 0.5201, 0.5996, 0.0135],
        [0.0330, 0.2814, 0.6120, 0.3422, 0.7293, 0.0113, 0.5273]])


### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**

In [6]:
tensor_A = torch.rand(7,7)
tensor_B = torch.rand(1,7)

# Matrix multiplication
# transpose B from (1,7) to (7,1)

result = torch.matmul(tensor_A, tensor_B.T)


print("tensor_A shape:", tensor_A.shape)
print("tensor_B shape:", tensor_B.shape)
print("tensor_B.T shape:", tensor_B.T.shape)
print("Result shape:", result.shape)
print("\nResult:\n", result)


tensor_A shape: torch.Size([7, 7])
tensor_B shape: torch.Size([1, 7])
tensor_B.T shape: torch.Size([7, 1])
Result shape: torch.Size([7, 1])

Result:
 tensor([[1.0489],
        [1.2963],
        [1.1005],
        [1.8712],
        [0.9479],
        [1.3027],
        [1.2920]])


### **Q3 Set the random seed to `0` and do Q1 & Q2 over again**

In [7]:
import torch

# Set random seed to 0
torch.manual_seed(0)

# Q1 - Random tensor of shape (7, 7)
tensor_A = torch.rand(7, 7)

# Q2 - Random tensor of shape (1, 7) and matrix multiplication
tensor_B = torch.rand(1, 7)
result = torch.matmul(tensor_A, tensor_B.T)

print("tensor_A:\n", tensor_A)
print("\ntensor_B:\n", tensor_B)
print("\nResult of matmul (tensor_A @ tensor_B.T):\n", result)
print("\nResult shape:", result.shape)

tensor_A:
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

tensor_B:
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

Result of matmul (tensor_A @ tensor_B.T):
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

Result shape: torch.Size([7, 1])


### **Q4 Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?**
  * If there is, set the GPU random seed to `1234`

In [8]:
import torch

# Set GPU random seed
torch.cuda.manual_seed(1234)


### **Q5 Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)**

In [10]:
import torch

# Q5 - Setup
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Q6 - Matrix multiplication (transpose B to match inner dims)
# (2, 3) @ (3, 2) -> (2, 2)
output = torch.matmul(tensor_A, tensor_B.T)

print(f"tensor_A shape: {tensor_A.shape}")
print(f"tensor_B shape: {tensor_B.shape}")
print(f"tensor_B.T shape: {tensor_B.T.shape}")
print(f"\nOutput:\n {output}")
print(f"Output shape: {output.shape}")

tensor_A shape: torch.Size([2, 3])
tensor_B shape: torch.Size([2, 3])
tensor_B.T shape: torch.Size([3, 2])

Output:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
Output shape: torch.Size([2, 2])



### **Q6 Perform a matrix multiplication on the tensors you created in Q5**

In [12]:
import torch

# Q5 - Setup
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Q6 - Matrix multiplication
output = torch.matmul(tensor_A, tensor_B.T)  # (2,3) @ (3,2) -> (2,2)

print(f"tensor_A shape: {tensor_A.shape}")
print(f"tensor_B shape: {tensor_B.shape}")
print(f"\nOutput:\n {output}")
print(f"Output shape: {output.shape}")

tensor_A shape: torch.Size([2, 3])
tensor_B shape: torch.Size([2, 3])

Output:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
Output shape: torch.Size([2, 2])


### **Q7 Find the maximum and minimum values of the output of Q6**

In [13]:
import torch

# Q5 - Setup
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Q6 - Matrix multiplication
output = torch.matmul(tensor_A, tensor_B.T)

# Q7 - Max and Min
print(f"Maximum value: {output.max()}")
print(f"Minimum value: {output.min()}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### **Q8 Find the index of the maximum and minimum values of the output of Q6**

In [14]:
import torch

# Q5 - Setup
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Q6 - Matrix multiplication
output = torch.matmul(tensor_A, tensor_B.T)

# Q8 - Index of Max and Min
print(f"Output:\n {output}")
print(f"\nIndex of Maximum value: {output.argmax()}")
print(f"Index of Minimum value: {output.argmin()}")

Output:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

Index of Maximum value: 3
Index of Minimum value: 0


### **Q9 Perform a matrix multiplication on the tensors you created in Q5 in `numpy` and convert the output to tensor**

In [15]:
import torch
import numpy as np

# Q5 - Setup
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Convert tensors to numpy (must be on CPU first)
numpy_A = tensor_A.cpu().numpy()
numpy_B = tensor_B.cpu().numpy()

# Perform matrix multiplication in numpy
numpy_output = np.matmul(numpy_A, numpy_B.T)

# Convert back to tensor
output

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### **Q10 Make a random tensor with shape `(1, 1, 1, 10)` and then convert it to a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape**

In [16]:
import torch

# Set seed
torch.manual_seed(7)

# Create tensor of shape (1, 1, 1, 10)
tensor = torch.rand(1, 1, 1, 10)

# Squeeze to shape (10)
tensor_squeezed = tensor.squeeze()

print(f"Original tensor:\n {tensor}")
print(f"Original shape: {tensor.shape}")
print(f"\nSqueezed tensor:\n {tensor_squeezed}")
print(f"Squeezed shape: {tensor_squeezed.shape}")

Original tensor:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original shape: torch.Size([1, 1, 1, 10])

Squeezed tensor:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed shape: torch.Size([10])
