# **PyTorch Fundamentals Exercise**



In [ ]:
# Import all the necessary libraries here

### **Q1 Create a random tensor with shape `(7, 7)`**


In [2]:
# Your code hereimport torch

# Create random tensor (7 rows, 7 columns)
import torch
x = torch.ones(7, 7)

print(x)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])


### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**

In [4]:
# Your codimport torch

# 7x7 tensor
A = torch.rand(7, 7)

# 1x7 tensor
B = torch.rand(1, 7)

# matrix multiplication
result = torch.matmul(B, A)

print("Shape:", result.shape)
print(result)
torch.Size([1, 7])

Shape: torch.Size([1, 7])
tensor([[2.1829, 2.1178, 1.6898, 1.2189, 0.6196, 1.6598, 1.7433]])


torch.Size([1, 7])

### **Q3 Set the random seed to `0` and do Q1 & Q2 over again**

In [7]:
# Your code herimport torch

# Set seed
torch.manual_seed(0)

# Create tensor
A = torch.rand(7, 7)

print(A)

# Create (1x7) tensor
B = torch.rand(1, 7)

# Multiply (1x7) × (7x7) → (1x7)
result = torch.matmul(B, A)

print("Shape:", result.shape)
print(result)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Shape: torch.Size([1, 7])
tensor([[2.1581, 1.9307, 2.8454, 2.6230, 1.9117, 2.0266, 1.4257]])


### **Q4 Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?**
  * If there is, set the GPU random seed to `1234`

In [8]:
torch.manual_seed(0)


### **Q5 Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)**

In [9]:
import torch

# Set seed (for reproducibility)
torch.manual_seed(1234)

# Create tensors on CPU
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)

# Check if GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"

# Move tensors to GPU
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

print("Device:", device)
print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)

Device: cuda
Tensor 1:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Tensor 2:
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### **Q6 Perform a matrix multiplication on the tensors you created in Q5**

In [10]:
import torch

torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

# Transpose tensor2
tensor2_T = tensor2.T

# Matrix multiplication
result = torch.matmul(tensor1, tensor2_T)

print("Result shape:", result.shape)
print(result)

Result shape: torch.Size([2, 2])
tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### **Q7 Find the maximum and minimum values of the output of Q6**

In [ ]:
# Your code here

### **Q8 Find the index of the maximum and minimum values of the output of Q6**

In [ ]:
# Your code here

### **Q9 Perform a matrix multiplication on the tensors you created in Q5 in `numpy` and convert the output to tensor**

In [ ]:
# Your code here


### **Q10 Make a random tensor with shape `(1, 1, 1, 10)` and then convert it to a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape**

In [ ]:
# Your code here